### ISSUE TITLE
#RegExp#字符串对象的方法

### ISSUE THREAD

**Issue by isLishude** [fe2017/frontend#2]
- [x] match()
- [x] search()
- [x] repalce()
- [x] split()

**Comment by isLishude** [comment]
字符串对象的方法之中，有4种与正则对象有关。

1. match()：返回一个数组，成员是所有匹配的子字符串。
2. search()：按照给定的正则表达式进行搜索，返回一个整数，表示匹配开始的位置。
3. replace()：按照给定的正则表达式进行替换，返回替换后的字符串。
4. split()：按照给定规则进行字符串分割，返回一个数组，包含分割后的各个成员。

**Comment by adetest** [comment]
## match()
字符串的match方法与正则对象的exec方法非常类似：匹配成功返回一个数组，匹配失败返回null。如果正则表达式带有g修饰符，则该方法与正则对象的exec方法行为不同，**会一次性返回所有匹配成功的结果**。

**Comment by adetest** [comment]
## search()
返回第一个满足条件的匹配结果在整个字符串中的位置。如果没有任何匹配，则返回-1。该方法会忽略g修饰符。

**Comment by adetest** [comment]
## replace()
字符串对象的replace方法可以替换匹配的值。它接受两个参数，第一个是搜索模式，第二个是替换的内容。如果有 g 修饰符会替换全部匹配成功的值。

```js
str.replace(search, replacement)
```

replace方法的第二个参数可以使用美元符号$，用来指代所替换的内容。

- `$&` 指代匹配的子字符串。
- `$`` 指代匹配结果前面的文本。
- `$' `指代匹配结果后面的文本。
- `$n` 指代匹配成功的第n组内容，n是从1开始的自然数。
- `$$` 指代美元符号$。

**Comment by isLishude** [comment]
## split()
字符串对象的split方法按照正则规则分割字符串，返回一个由分割后的各个部分组成的数组。该方法接受两个参数，第一个参数是分隔规则，第二个参数是返回数组的最大成员数。

```js
// 非正则分隔
'a,  b,c, d'.split(',')
// [ 'a', '  b', 'c', ' d' ]

// 正则分隔，去除多余的空格
'a,  b,c, d'.split(/,\s*/)
// [ 'a', 'b', 'c', 'd' ]

// 指定返回数组的最大成员数
'a,  b,c, d'.split(/, */, 2)
[ 'a', 'b' ]
```

**Comment by isLishude** [comment]
## match()
字符串的match方法与正则对象的exec方法非常类似：匹配成功返回一个数组，匹配失败返回null。如果正则表达式带有g修饰符，则该方法与正则对象的exec方法行为不同，**会一次性返回所有匹配成功的结果**。

设置正则表达式的 lastIndex 属性，对match方法无效，匹配总是从字符串的第一个字符开始。

From <http://javascript.ruanyifeng.com/stdlib/regexp.html>

**Comment by isLishude** [comment]
## replace()
字符串对象的replace方法可以替换匹配的值。它接受两个参数，第一个是搜索模式，第二个是替换的内容。如果有 g 修饰符会替换全部匹配成功的值。

```js
str.replace(search, replacement)
```

replace方法的第二个参数可以使用美元符号 $，用来指代所替换的内容。

```
$& 指代匹配的子字符串。
$` 指代匹配结果前面的文本。
$' 指代匹配结果后面的文本。
$n 指代匹配成功的第n组内容，n是从1开始的自然数。
$$ 指代美元符号$。
```

例子： 

```js
'hello world'.replace(/(\w+)\s(\w+)/, '$2 $1')
// "world hello"

'abc'.replace('b', '[$`-$&-$\']')
// "a[a-b-c]c"
```

作为replace方法第二个参数的替换函数，可以接受多个参数。第一个参数是捕捉到的内容，第二个参数是捕捉到的组匹配（有多少个组匹配，就有多少个对应的参数）。此外，最后还可以添加两个参数，倒数第二个参数是捕捉到的内容在整个字符串中的位置（比如从第五个位置开始），最后一个参数是原字符串。下面是一个网页模板替换的例子。

```js
var prices = {
  'pr_1': '$1.99',
  'pr_2': '$9.99',
  'pr_3': '$5.00'
};

var template = '/* ... */'; // 这里可以放网页模块字符串

template.replace(
  /(<span id=")(.*?)(">)(<\/span>)/g,
  function(match, $1, $2, $3, $4){
    return $1 + $2 + $3 + prices[$2] + $4;
  }
);
```

From <http://javascript.ruanyifeng.com/stdlib/regexp.html>

**Comment by isLishude** [comment]
## search()
返回第一个满足条件的匹配结果在整个字符串中的位置。如果没有任何匹配，则返回-1。该方法会忽略g修饰符。

From <http://javascript.ruanyifeng.com/stdlib/regexp.html>
